revoke delete on table "public"."product_files" from "anon";

revoke insert on table "public"."product_files" from "anon";

revoke references on table "public"."product_files" from "anon";

revoke select on table "public"."product_files" from "anon";

revoke trigger on table "public"."product_files" from "anon";

revoke truncate on table "public"."product_files" from "anon";

revoke update on table "public"."product_files" from "anon";

revoke delete on table "public"."product_files" from "authenticated";

revoke insert on table "public"."product_files" from "authenticated";

revoke references on table "public"."product_files" from "authenticated";

revoke select on table "public"."product_files" from "authenticated";

revoke trigger on table "public"."product_files" from "authenticated";

revoke truncate on table "public"."product_files" from "authenticated";

revoke update on table "public"."product_files" from "authenticated";

revoke delete on table "public"."product_files" from "service_role";

revoke insert on table "public"."product_files" from "service_role";

revoke references on table "public"."product_files" from "service_role";

revoke select on table "public"."product_files" from "service_role";

revoke trigger on table "public"."product_files" from "service_role";

revoke truncate on table "public"."product_files" from "service_role";

revoke update on table "public"."product_files" from "service_role";

alter table "public"."product_files" drop constraint "product_files_prod_id_fkey";

alter table "public"."product_files" drop constraint "product_files_pkey";

alter table "public"."product_category" drop constraint "product_category_pkey";

drop index if exists "public"."product_files_pkey";

drop index if exists "public"."product_category_pkey";

drop table "public"."product_files";

create table "public"."product_market_place" (
    "prod_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "price_new" numeric,
    "extern_price" numeric,
    "intern_price" numeric,
    "buyer_price" boolean default false,
    "pick_up_on_site" boolean default false,
    "send_with_freight" boolean default false,
    "address" text,
    "postal_code" text,
    "locality" text,
    "comment" text,
    "contact_person" uuid
);


alter table "public"."product_market_place" enable row level security;

alter table "public"."category" alter column "parent_id" drop not null;

alter table "public"."product_category" add column "id" bigint generated by default as identity not null;

alter table "public"."product_individual" drop column "accessibility_description";

alter table "public"."product_individual" drop column "address";

alter table "public"."product_individual" drop column "articel_number";

alter table "public"."product_individual" drop column "avg_height_max";

alter table "public"."product_individual" drop column "avg_height_min";

alter table "public"."product_individual" drop column "bk04";

alter table "public"."product_individual" drop column "bought_year";

alter table "public"."product_individual" drop column "bsab";

alter table "public"."product_individual" drop column "burglary_resistance_class";

alter table "public"."product_individual" drop column "buyer_price";

alter table "public"."product_individual" drop column "color_finish";

alter table "public"."product_individual" drop column "comment";

alter table "public"."product_individual" drop column "depth";

alter table "public"."product_individual" drop column "diameter";

alter table "public"."product_individual" drop column "disassembly_description";

alter table "public"."product_individual" drop column "enr";

alter table "public"."product_individual" drop column "environmental_profile";

alter table "public"."product_individual" drop column "extern_price";

alter table "public"."product_individual" drop column "fire_resistance_class";

alter table "public"."product_individual" drop column "frame_depth";

alter table "public"."product_individual" drop column "glass_model";

alter table "public"."product_individual" drop column "glass_thickness";

alter table "public"."product_individual" drop column "glass_type";

alter table "public"."product_individual" drop column "gtin";

alter table "public"."product_individual" drop column "hanging";

alter table "public"."product_individual" drop column "height";

alter table "public"."product_individual" drop column "intern_price";

alter table "public"."product_individual" drop column "locality";

alter table "public"."product_individual" drop column "lumbal_support";

alter table "public"."product_individual" drop column "manufactor";

alter table "public"."product_individual" drop column "manufactor_year";

alter table "public"."product_individual" drop column "material";

alter table "public"."product_individual" drop column "module_size";

alter table "public"."product_individual" drop column "pick_up_on_site";

alter table "public"."product_individual" drop column "postal_code";

alter table "public"."product_individual" drop column "price_new";

alter table "public"."product_individual" drop column "rsk";

alter table "public"."product_individual" drop column "send_with_freight";

alter table "public"."product_individual" drop column "sound_reduction";

alter table "public"."product_individual" drop column "thickness";

alter table "public"."product_individual" drop column "unit_of_measure";

alter table "public"."product_individual" drop column "weight";

alter table "public"."product_individual" drop column "weight_unit";

alter table "public"."product_individual" drop column "width";

alter table "public"."product_individual" alter column "availability" set data type date using "availability"::date;

alter table "public"."product_individual" alter column "delivery" set data type date using "delivery"::date;

alter table "public"."products" drop column "image";

alter table "public"."products" add column "files" text[];

alter table "public"."products" add column "images" text[];

alter table "public"."products" alter column "visual_condition" drop default;

alter table "public"."products" alter column "visual_condition" drop not null;

alter table "public"."products" alter column "visual_condition" set data type text using "visual_condition"::text;

alter table "public"."products" alter column "working_condition" drop default;

alter table "public"."products" alter column "working_condition" set data type text using "working_condition"::text;

CREATE UNIQUE INDEX product_market_place_pkey ON public.product_market_place USING btree (prod_id);

CREATE UNIQUE INDEX product_category_pkey ON public.product_category USING btree (id);

alter table "public"."product_market_place" add constraint "product_market_place_pkey" PRIMARY KEY using index "product_market_place_pkey";

alter table "public"."product_category" add constraint "product_category_pkey" PRIMARY KEY using index "product_category_pkey";

alter table "public"."product_market_place" add constraint "product_market_place_contact_person_fkey" FOREIGN KEY (contact_person) REFERENCES profile(id) not valid;

alter table "public"."product_market_place" validate constraint "product_market_place_contact_person_fkey";

alter table "public"."product_market_place" add constraint "product_market_place_prod_id_fkey" FOREIGN KEY (prod_id) REFERENCES products(id) ON DELETE CASCADE not valid;

alter table "public"."product_market_place" validate constraint "product_market_place_prod_id_fkey";

grant delete on table "public"."product_market_place" to "anon";

grant insert on table "public"."product_market_place" to "anon";

grant references on table "public"."product_market_place" to "anon";

grant select on table "public"."product_market_place" to "anon";

grant trigger on table "public"."product_market_place" to "anon";

grant truncate on table "public"."product_market_place" to "anon";

grant update on table "public"."product_market_place" to "anon";

grant delete on table "public"."product_market_place" to "authenticated";

grant insert on table "public"."product_market_place" to "authenticated";

grant references on table "public"."product_market_place" to "authenticated";

grant select on table "public"."product_market_place" to "authenticated";

grant trigger on table "public"."product_market_place" to "authenticated";

grant truncate on table "public"."product_market_place" to "authenticated";

grant update on table "public"."product_market_place" to "authenticated";

grant delete on table "public"."product_market_place" to "service_role";

grant insert on table "public"."product_market_place" to "service_role";

grant references on table "public"."product_market_place" to "service_role";

grant select on table "public"."product_market_place" to "service_role";

grant trigger on table "public"."product_market_place" to "service_role";

grant truncate on table "public"."product_market_place" to "service_role";

grant update on table "public"."product_market_place" to "service_role";

create policy "allow all"
on "public"."category"
as permissive
for all
to public
using (true);


create policy "allow all"
on "public"."product_category"
as permissive
for all
to public
using (true);


create policy "allow all"
on "public"."product_individual"
as permissive
for select
to public
using (true);


create policy "allow all"
on "public"."product_market_place"
as permissive
for all
to public
using (true);


create policy "allow all"
on "public"."product_property"
as permissive
for select
to public
using (true);


create policy "allow all"
on "public"."products"
as permissive
for select
to public
using (true);


create policy "allow all"
on "public"."projects"
as permissive
for all
to public
using (true);



