create table "public"."category" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "parent_id" uuid not null
);


alter table "public"."category" enable row level security;

create table "public"."product_category" (
    "product_id" uuid not null,
    "category_id" uuid,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."product_category" enable row level security;

create table "public"."product_files" (
    "id" bigint generated by default as identity not null,
    "prod_id" uuid not null,
    "file_url" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."product_files" enable row level security;

create table "public"."product_individual" (
    "id" bigint generated by default as identity not null,
    "prod_id" uuid not null,
    "amount" bigint not null default '1'::bigint,
    "prod_status" text,
    "market_status" text,
    "availability" timestamp with time zone,
    "delivery" timestamp with time zone,
    "disassembly" text,
    "disassembly_description" text,
    "accessibility" text,
    "accessibility_description" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."product_individual" enable row level security;

create table "public"."product_property" (
    "id" bigint generated by default as identity not null,
    "prod_id" uuid not null,
    "name" text,
    "value" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."product_property" enable row level security;

create table "public"."products" (
    "id" uuid not null default gen_random_uuid(),
    "name" text,
    "project_id" uuid not null,
    "visual_condition" smallint not null default '0'::smallint,
    "working_condition" smallint default '0'::smallint,
    "image" text,
    "description" text,
    "product_id" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."products" enable row level security;

create table "public"."projects" (
    "id" uuid not null default gen_random_uuid(),
    "name" text,
    "country" text[],
    "region" text[],
    "currency" text,
    "image" text,
    "project_number" text,
    "user_id" uuid default auth.uid(),
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."projects" enable row level security;

CREATE UNIQUE INDEX category_pkey ON public.category USING btree (id);

CREATE UNIQUE INDEX product_category_pkey ON public.product_category USING btree (product_id);

CREATE UNIQUE INDEX product_files_pkey ON public.product_files USING btree (id);

CREATE UNIQUE INDEX product_individual_pkey ON public.product_individual USING btree (id);

CREATE UNIQUE INDEX product_property_pkey ON public.product_property USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

alter table "public"."category" add constraint "category_pkey" PRIMARY KEY using index "category_pkey";

alter table "public"."product_category" add constraint "product_category_pkey" PRIMARY KEY using index "product_category_pkey";

alter table "public"."product_files" add constraint "product_files_pkey" PRIMARY KEY using index "product_files_pkey";

alter table "public"."product_individual" add constraint "product_individual_pkey" PRIMARY KEY using index "product_individual_pkey";

alter table "public"."product_property" add constraint "product_property_pkey" PRIMARY KEY using index "product_property_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."category" add constraint "category_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES category(id) not valid;

alter table "public"."category" validate constraint "category_parent_id_fkey";

alter table "public"."product_category" add constraint "product_category_category_id_fkey" FOREIGN KEY (category_id) REFERENCES category(id) not valid;

alter table "public"."product_category" validate constraint "product_category_category_id_fkey";

alter table "public"."product_category" add constraint "product_category_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE not valid;

alter table "public"."product_category" validate constraint "product_category_product_id_fkey";

alter table "public"."product_files" add constraint "product_files_prod_id_fkey" FOREIGN KEY (prod_id) REFERENCES products(id) ON DELETE CASCADE not valid;

alter table "public"."product_files" validate constraint "product_files_prod_id_fkey";

alter table "public"."product_individual" add constraint "product_individual_prod_id_fkey" FOREIGN KEY (prod_id) REFERENCES products(id) ON DELETE CASCADE not valid;

alter table "public"."product_individual" validate constraint "product_individual_prod_id_fkey";

alter table "public"."product_property" add constraint "product_property_prod_id_fkey" FOREIGN KEY (prod_id) REFERENCES products(id) ON DELETE CASCADE not valid;

alter table "public"."product_property" validate constraint "product_property_prod_id_fkey";

alter table "public"."products" add constraint "products_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."products" validate constraint "products_project_id_fkey";

alter table "public"."projects" add constraint "projects_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profile(id) ON DELETE CASCADE not valid;

alter table "public"."projects" validate constraint "projects_user_id_fkey";

grant delete on table "public"."category" to "anon";

grant insert on table "public"."category" to "anon";

grant references on table "public"."category" to "anon";

grant select on table "public"."category" to "anon";

grant trigger on table "public"."category" to "anon";

grant truncate on table "public"."category" to "anon";

grant update on table "public"."category" to "anon";

grant delete on table "public"."category" to "authenticated";

grant insert on table "public"."category" to "authenticated";

grant references on table "public"."category" to "authenticated";

grant select on table "public"."category" to "authenticated";

grant trigger on table "public"."category" to "authenticated";

grant truncate on table "public"."category" to "authenticated";

grant update on table "public"."category" to "authenticated";

grant delete on table "public"."category" to "service_role";

grant insert on table "public"."category" to "service_role";

grant references on table "public"."category" to "service_role";

grant select on table "public"."category" to "service_role";

grant trigger on table "public"."category" to "service_role";

grant truncate on table "public"."category" to "service_role";

grant update on table "public"."category" to "service_role";

grant delete on table "public"."product_category" to "anon";

grant insert on table "public"."product_category" to "anon";

grant references on table "public"."product_category" to "anon";

grant select on table "public"."product_category" to "anon";

grant trigger on table "public"."product_category" to "anon";

grant truncate on table "public"."product_category" to "anon";

grant update on table "public"."product_category" to "anon";

grant delete on table "public"."product_category" to "authenticated";

grant insert on table "public"."product_category" to "authenticated";

grant references on table "public"."product_category" to "authenticated";

grant select on table "public"."product_category" to "authenticated";

grant trigger on table "public"."product_category" to "authenticated";

grant truncate on table "public"."product_category" to "authenticated";

grant update on table "public"."product_category" to "authenticated";

grant delete on table "public"."product_category" to "service_role";

grant insert on table "public"."product_category" to "service_role";

grant references on table "public"."product_category" to "service_role";

grant select on table "public"."product_category" to "service_role";

grant trigger on table "public"."product_category" to "service_role";

grant truncate on table "public"."product_category" to "service_role";

grant update on table "public"."product_category" to "service_role";

grant delete on table "public"."product_files" to "anon";

grant insert on table "public"."product_files" to "anon";

grant references on table "public"."product_files" to "anon";

grant select on table "public"."product_files" to "anon";

grant trigger on table "public"."product_files" to "anon";

grant truncate on table "public"."product_files" to "anon";

grant update on table "public"."product_files" to "anon";

grant delete on table "public"."product_files" to "authenticated";

grant insert on table "public"."product_files" to "authenticated";

grant references on table "public"."product_files" to "authenticated";

grant select on table "public"."product_files" to "authenticated";

grant trigger on table "public"."product_files" to "authenticated";

grant truncate on table "public"."product_files" to "authenticated";

grant update on table "public"."product_files" to "authenticated";

grant delete on table "public"."product_files" to "service_role";

grant insert on table "public"."product_files" to "service_role";

grant references on table "public"."product_files" to "service_role";

grant select on table "public"."product_files" to "service_role";

grant trigger on table "public"."product_files" to "service_role";

grant truncate on table "public"."product_files" to "service_role";

grant update on table "public"."product_files" to "service_role";

grant delete on table "public"."product_individual" to "anon";

grant insert on table "public"."product_individual" to "anon";

grant references on table "public"."product_individual" to "anon";

grant select on table "public"."product_individual" to "anon";

grant trigger on table "public"."product_individual" to "anon";

grant truncate on table "public"."product_individual" to "anon";

grant update on table "public"."product_individual" to "anon";

grant delete on table "public"."product_individual" to "authenticated";

grant insert on table "public"."product_individual" to "authenticated";

grant references on table "public"."product_individual" to "authenticated";

grant select on table "public"."product_individual" to "authenticated";

grant trigger on table "public"."product_individual" to "authenticated";

grant truncate on table "public"."product_individual" to "authenticated";

grant update on table "public"."product_individual" to "authenticated";

grant delete on table "public"."product_individual" to "service_role";

grant insert on table "public"."product_individual" to "service_role";

grant references on table "public"."product_individual" to "service_role";

grant select on table "public"."product_individual" to "service_role";

grant trigger on table "public"."product_individual" to "service_role";

grant truncate on table "public"."product_individual" to "service_role";

grant update on table "public"."product_individual" to "service_role";

grant delete on table "public"."product_property" to "anon";

grant insert on table "public"."product_property" to "anon";

grant references on table "public"."product_property" to "anon";

grant select on table "public"."product_property" to "anon";

grant trigger on table "public"."product_property" to "anon";

grant truncate on table "public"."product_property" to "anon";

grant update on table "public"."product_property" to "anon";

grant delete on table "public"."product_property" to "authenticated";

grant insert on table "public"."product_property" to "authenticated";

grant references on table "public"."product_property" to "authenticated";

grant select on table "public"."product_property" to "authenticated";

grant trigger on table "public"."product_property" to "authenticated";

grant truncate on table "public"."product_property" to "authenticated";

grant update on table "public"."product_property" to "authenticated";

grant delete on table "public"."product_property" to "service_role";

grant insert on table "public"."product_property" to "service_role";

grant references on table "public"."product_property" to "service_role";

grant select on table "public"."product_property" to "service_role";

grant trigger on table "public"."product_property" to "service_role";

grant truncate on table "public"."product_property" to "service_role";

grant update on table "public"."product_property" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."projects" to "anon";

grant insert on table "public"."projects" to "anon";

grant references on table "public"."projects" to "anon";

grant select on table "public"."projects" to "anon";

grant trigger on table "public"."projects" to "anon";

grant truncate on table "public"."projects" to "anon";

grant update on table "public"."projects" to "anon";

grant delete on table "public"."projects" to "authenticated";

grant insert on table "public"."projects" to "authenticated";

grant references on table "public"."projects" to "authenticated";

grant select on table "public"."projects" to "authenticated";

grant trigger on table "public"."projects" to "authenticated";

grant truncate on table "public"."projects" to "authenticated";

grant update on table "public"."projects" to "authenticated";

grant delete on table "public"."projects" to "service_role";

grant insert on table "public"."projects" to "service_role";

grant references on table "public"."projects" to "service_role";

grant select on table "public"."projects" to "service_role";

grant trigger on table "public"."projects" to "service_role";

grant truncate on table "public"."projects" to "service_role";

grant update on table "public"."projects" to "service_role";


